"""empty message

Revision ID: be7801f007c4
Revises: 
Create Date: 2019-01-07 17:27:01.285001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7801f007c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('languages')
    op.drop_table('messages')
    op.add_column('user', sa.Column('date_published', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_published')
    op.create_table('messages',
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(length=140), autoincrement=False, nullable=True)
    )
    op.create_table('languages',
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('developer', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
